# WORKING

In [1]:
import numpy as np
import pandas as pd

In [2]:
INPUT_FILE = 'input.txt'

In [3]:
with open(INPUT_FILE, 'r') as f:
    lines = [line.strip('\n') for line in f.readlines()]
    
# lines

In [4]:
# Example input, same format as "lines"

example_tree_grid = [
    '30373',
    '25512',
    '65332',
    '33549',
    '35390'
]

---

## Create Tree Grid

In [20]:
def create_tree_grid(lines):
    """Create an array from a list of numeric strings."""
    rows = [[int(num) for num in list(line)] for line in lines]
    rows = np.array(rows)
    return rows

In [21]:
tree_grid = create_tree_grid(example_tree_grid)

# tree_grid = create_tree_grid(lines)
tree_grid

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

---

## Create Empty Grid to Hold Checked Trees

In [22]:
def create_checked_grid(tree_grid):
    num_of_rows = tree_grid.shape[0]
    num_of_columns = tree_grid.shape[1]
    
    checked_grid = np.zeros((num_of_rows, num_of_columns), dtype=np.int16)   

    return checked_grid

In [23]:
checked_grid = create_checked_grid(tree_grid)
checked_grid

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [26]:
def add_edge_trees_to_checked_grid(tree_grid):

    last_row_index = len(tree_grid) - 1

    # Check every row in the tree grid, and keep track of the index of the current row
    for row_number, row in enumerate(tree_grid):
        # Check every tree in each row, and keep track of the index of the current tree    
        for tree_number, tree in enumerate(row):
            # Add a 1 to the tree's location in the checked grid if the tree is on the edge
            # of the grid
            if (
                (row_number == 0) or (row_number == last_row_index) or 
                (tree_number == 0) or (tree_number == len(row) - 1)
            ):
                checked_grid[row_number][tree_number] = 1

            # Otherwise, keep track of each inner tree's neighbors.

    return checked_grid
    
checked_grid = add_edge_trees_to_checked_grid(tree_grid)
checked_grid
        

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

---

# IN PROGRESS

In [34]:
def look_down_row(tree_grid):
    
    # Save row, column point for each visible tree to this list
    all_visible = []

    # Enumerate through each row in the tree grid
    for i, row in enumerate(tree_grid):
        # Find the tallest tree for that row
        tallest_tree_height = max(row)
        
        # Enumerate through the trees in each row
        for j, tree in enumerate(row):
            # If the tree is the first tree in the row
            if j == 0:
                # We don't need to explicitly add it to all_visible
                # because all the edge trees were added with the add_edge_trees
                # function
                # We do need to set the first tree for comparison to the rest
                # of the trees
                current_tree = row[j]
                # But if the current tree is the first tallest tree, then stop there.
                if current_tree == tallest_tree_height:
                    break
                # Otherwise, continue checking the trees in the row.
                else:
                    continue
            
            # If the tree is not the first in the row and the tree equals the 
            # tallest tree height 
            elif tree == tallest_tree_height:
                # Add that tree's point to the list of visible trees
                all_visible.append([i, j])
                # And then stop
                break
            # Otherwise, if the tree is not the first tree in the row and it does not
            # equal the tallest tree
            elif tree != tallest_tree_height:
                # If the tree's height is taller than the current tree's height
                if tree > current_tree:
                    # Add that tree's points to the list of visible trees
                    all_visible.append([i, j])
                    # Then, set the current tree to that tree, so that any tree after
                    # it must be higher than it to be visible
                    current_tree = tree
                # If the tree's height is equal to or smaller than the current tree's
                # height, it will not be visible, so we can continue our search
                # to find visible trees in the row
                elif tree <= current_tree:
                    continue
                    

        
    # Returns a list of lists, where each sublist has two integers: one to represent
    # the row, and one to represent the column of each visible tree in the tree_grid
    # matrix.                    
    return all_visible

In [94]:

tree_grid_copy = tree_grid
reversed_tree_grid = []

for row in tree_grid_copy:
    reversed_row = row[::-1]
    reversed_tree_grid.append(reversed_row)
    
reversed_tree_grid = np.array(reversed_tree_grid)
reversed_tree_grid


reversed_visible_points = look_down_row(reversed_tree_grid)
reversed_visible_points


for point in reversed_visible_points:
    new_point = []
    row, column = point
    last_index = len(tree_grid[0]) - 1
    print([row, last_index - column])

[0, 3]
[1, 2]
[2, 3]
[2, 1]
[2, 0]
[4, 3]


In [37]:
visible_points = look_down_row(tree_grid)
visible_points

for point in visible_points:
    row, column = point

[[0, 3], [1, 1], [3, 2], [3, 4], [4, 1], [4, 3]]

In [50]:
def update_checked_grid(visible_points):

    for point in visible_points:
        row, column = point
        checked_grid[row][column] = 1
        
    return checked_grid

update_checked_grid(visible_points)

array([[1, 1, 1, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)